name: mobile
description: "Мобилно приложение за намиране на nRF52840 тагове чрез ESP32 рутери."
publish_to: "none"

version: 0.2.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  go_router: ^17.0.0
  google_nav_bar: ^5.0.7
  mqtt_client: ^10.11.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.10.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  android_adaptive_icon_background: "assets/icon/app_icon.png"
  android_adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
